daemonize = true
max_history = 100
synchronize_selection_with_clipboard = true
snippets = []

[dbus]
enable = true

[desktop_notification]
enable = true
icon = "accessories-clipboard"
timeout_ms = 2000
long_plaintext_length = 2000

[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "error"

[metrics]
enable = true
host = "127.0.0.1"
port = 45047

[watcher]
enable_clipboard = true
enable_primary = true
enable_secondary = false
sensitive_x11_atoms = ["x-kde-passwordManagerHint"]
filter_text_min_length = 1
filter_text_max_length = 20000000
denied_text_regex_patterns = []
capture_image = true
filter_image_max_size = 5242880
