#!/usr/bin/env sh

$XMONAD_GHC --make xmonad.hs \
  -i -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -O2 \
  -optc-O3 -optl-O3 \
  -fstrictness -funbox-strict-fields \
  -fspecialise-aggressively \
  -fcross-module-specialise \
  -fno-full-laziness \
  -fno-state-hack \
  -optc-ffast-math \
  -optc-fno-stack-protector -optc-DNDEBUG -optl-fno-stack-protector \
  -optc-fomit-frame-pointer \
  -optc-ffunction-sections -optc-fdata-sections \
  -optl-Wl,--gc-sections,--as-needed \
  -optc-fno-plt \
  -optc-fno-semantic-interposition \
  -optc-fmerge-all-constants \
  -optl-Wl,-O3,--sort-common,--as-needed \
  -optl-s \
  -o "$1"
