#! /bin/sh

sxhkd ~/.config/sxhkd/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config initial_polarity second_child
# bspc config focus_follows_pointer true

# Pywal Colors

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a "Yad" state=floating
bspc rule -a Galculator state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a St:float state=floating
bspc rule -a zathura state=tiled


~/.config/polybar/launch.sh &

# bash /home/leniviy/.config/bspwm/bspwm_colors.sh &

# bspc subscribe node_add node_remove | while read line; do $HOME/.config/bspwm/dynamic-gaps.sh; done
