function loaad --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LO_OPTIONS' --description 'alias loaad eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LO_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LO_OPTIONS $argv
        
end
