function loaa --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAA_OPTIONS $EZA_LO_OPTIONS' --description 'alias loaa eza $EZA_STANDARD_OPTIONS $EZA_LAA_OPTIONS $EZA_LO_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAA_OPTIONS $EZA_LO_OPTIONS $argv
        
end
