function loaai --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LO_OPTIONS' --description 'alias loaai eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LO_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LO_OPTIONS $argv
        
end
