function loaaid --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LO_OPTIONS' --description 'alias loaaid eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LO_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LO_OPTIONS $argv
        
end
