function ltaaid --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltaaid eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAID_OPTIONS $EZA_LT_OPTIONS $argv
        
end
