function ltaai --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltaai eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS $argv
        
end
