function ltaad --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltaad eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAD_OPTIONS $EZA_LT_OPTIONS $argv
        
end
