function ltad --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltad eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LT_OPTIONS $argv
        
end
