function ltaid --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAID_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltaid eza $EZA_STANDARD_OPTIONS $EZA_LAID_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAID_OPTIONS $EZA_LT_OPTIONS $argv
        
end
