function ltai --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAI_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltai eza $EZA_STANDARD_OPTIONS $EZA_LAI_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAI_OPTIONS $EZA_LT_OPTIONS $argv
        
end
