#!/bin/sh -eu

SRC_DIR="$HOME/.xmonad"
EXE_NAME="xmonad-ng"
OUT="$1"

shift

cd "$SRC_DIR" || exit 1

cabal new-configure \
	--enable-optimization \
	--enable-executable-stripping

cabal new-build

find "$SRC_DIR"/dist-newstyle -type f -executable -name "$EXE_NAME" \
    -exec mv -u '{}' "$OUT" ';'
