#!/bin/sh

get_icon() {
	case $1 in
	# Icons for weather-icons
	01d) icon="" ;;
	01n) icon="" ;;
	02d) icon="" ;;
	02n) icon="" ;;
	03*) icon="" ;;
	04*) icon="" ;;
	09d) icon="" ;;
	09n) icon="" ;;
	10d) icon="" ;;
	10n) icon="" ;;
	11d) icon="" ;;
	11n) icon="" ;;
	13d) icon="" ;;
	13n) icon="" ;;
	50d) icon="" ;;
	50n) icon="" ;;
	*) icon="" ;;

	esac

	echo $icon
}

get_duration() {

	osname=$(uname -s)

	case $osname in
	*BSD) date -r "$1" -u +%H:%M ;;
	*) date --date="@$1" -u +%H:%M ;;
	esac

}

## Openweathermap api_key
KEY=""
UNITS="metric"
SYMBOL="°"

API="https://api.openweathermap.org/data/2.5"

if [ -n "$CITY" ]; then
	if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
		CITY_PARAM="id=$CITY"
	else
		CITY_PARAM="q=$CITY"
	fi

	current=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
	forecast=$(curl -sf "$API/forecast?appid=$KEY&$CITY_PARAM&units=$UNITS&cnt=1")
else
	location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

	if [ -n "$location" ]; then
		location_lat="$(echo "$location" | jq '.location.lat')"
		location_lon="$(echo "$location" | jq '.location.lng')"

		current=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
		forecast=$(curl -sf "$API/forecast?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS&cnt=1")
	fi
fi

if [ -n "$current" ] && [ -n "$forecast" ]; then
	current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
	current_icon=$(echo "$current" | jq -r ".weather[0].icon")

	forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
	forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[0].icon")

	if [ "$current_temp" -gt "$forecast_temp" ]; then
		trend="<fn=3></fn>"
	elif [ "$forecast_temp" -gt "$current_temp" ]; then
		trend="<fn=3></fn>"
	else
		trend="<fn=3></fn>"
	fi

	echo "<fn=3>$(get_icon "$current_icon")</fn> / $current_temp$SYMBOL  $trend  <fn=3>$(get_icon "$forecast_icon")</fn> / $forecast_temp$SYMBOL"
fi
