export LANG=en_US.UTF-8

skip_global_compinit=1

# Home-manager sessionVariables
source /etc/profiles/per-user/leniviy/etc/profile.d/hm-session-vars.sh

## Auto-generated by my nix config
[ -f "${0:a:h}/extra.zshenv" ] && source "${0:a:h}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
