export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export LANG=en_US.UTF-8

# emacs
# export ALTERNATE_EDITOR=""
# export EDITOR="emacsclient -c"
# export VISUAL="emacsclient -c"

# export QT_QPA_PLATFORMTHEME="qt5ct"
export PF_INFO="ascii title os kernel uptime pkgs shell wm"
export NNN_PLUG='o:fzy-open;p:mocplay;d:ndiff;m:nmount;n:notes;v:viuimg;t:thumb'
export NNN_USE_EDITOR=1

## Auto-generated by my nix config
[ -f "${0:a:h}/extra.zshenv" ] && source "${0:a:h}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
