#!/usr/bin/env bash

current_layout=""
previous_layout=""

while read -r event; do
  if [[ $event != "$previous_layout" ]]; then
    current_layout="$event"
    xmonadctl -a XMONAD_SHOW_TEXT "${current_layout^^}"
    previous_layout="$event"
  fi
done < <(xkbmon)
