# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey
headerStyle: clean
statusStyle: "dot"
hideVersion: true
cardBlur: sm
language: en
quicklaunch:
  hideInternetSearch: true
  hideVisitURL: true
  searchDescriptions: true
