name: Formatting

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: nix fmt

      - name: Lint errors fixing
        run: nix run nixpkgs#statix fix .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
