name: Formatting

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install formatter
        run: "nix-env -iA nixpkgs-fmt -f '<nixpkgs>'"

      - name: Format
        run: nixpkgs-fmt .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
