name: Tests

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://nixos-nix-install-tests.cachix.org/serve/shrv10mfc5qxrg2b21j59fldhga5d8rs/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Check | Evaluate nix exressions
        run: nix flake check
